ALTER TABLE review_aspect_sentiments
ADD COLUMN IF NOT EXISTS analysis_payload JSONB,
ADD COLUMN IF NOT EXISTS language_code VARCHAR(20),
ADD COLUMN IF NOT EXISTS language_confidence DOUBLE PRECISION,
ADD COLUMN IF NOT EXISTS intent_label VARCHAR(50),
ADD COLUMN IF NOT EXISTS urgency_level VARCHAR(20),
ADD COLUMN IF NOT EXISTS experience_score INT,
ADD COLUMN IF NOT EXISTS impact_score DOUBLE PRECISION;
